// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d14c96ff-f8cd-49ff-9f0b-825a2792a0be",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6Bd5Zyhoo",
    "aws_user_pools_web_client_id": "3dqh9fdhvkpaup8rdb2ueroli",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://46im6i6yb5fz7eczhc2iwiupve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
